[project]
name = "pandaslecture"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.17.2",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]

[tool.marimo.display]
default_width = "full"
